apiVersion: apps/v1
kind: Deployment
metadata:
  name: vle8-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vle8
      version: green
  template:
    metadata:
      labels:
        app: vle8
        version: green
    spec:
      containers:
      - name: vle8
        image: spandanduari/vle8-app:latest
        env:
        - name: VERSION
          value: "GREEN"
        ports:
        - containerPort: 3000