apiVersion: v1
kind: Service
metadata:
  name: vle8-service
spec:
  type: NodePort
  selector:
    app: vle8
    version: blue   # initially BLUE is live
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30008